name: Invitation to the Lafraguru GitHub organization
description: I would like to be part of the awesome community
title: "Please invite me to the GitHub Community Organization"
labels: [github-invitation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
