name: Welcome to Catcrop!!!
description: I would like to be part of the awesome community
title: "Please invite me to the GitHub Community Organization"
labels: [github-invitation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Abir#9774
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Why do you want to join Tech Phantoms? What stuff you are excited to learn or build at Laraguru?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        We also have other amazing repositories! Check them out [here](https://github.com/catcrop).
