on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: github-invitation
        uses: vj-abigo/invite-on-label@v1.3
        with:
          organization: catcrop
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to CatCrop.'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}