on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: github-invitation
        uses: vj-abigo/invite-on-label@v1.3
        with:
          organization: laraguru
          label: github-invitation
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to the Org.'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
